export CLICOLOR=1
export GO111MODULE="auto"
export GOPATH="${HOME}/.go"
export NVM_DIR="${HOME}/.nvm"
export WASMER_DIR="${HOME}/.wasmer"
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export BASE16_THEME=gruvbox-dark-medium
export NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED=true
. "$HOME/.cargo/env"
